<a href="https://colab.research.google.com/github/osoliman/DSC110/blob/main/Description/DSC110_Description_Cleaning_Summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

#DataFrame in Python is the equivalent of table in SQL
df = pd.read_csv("https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv")

In [3]:
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [4]:
df.tail()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [5]:
df.head(20)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
5,130383.0,2.0,3.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN
6,130384.0,1.0,43.0,1.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN
7,130385.0,2.0,65.0,3.0,3.0,NaN,NaN,NaN,2.0,NaN,NaN
8,130386.0,1.0,34.0,1.0,4.0,30.2,173.3,110.0,2.0,5.1,100.0
9,130387.0,2.0,68.0,3.0,5.0,42.6,155.9,143.0,2.0,5.9,NaN
10,130388.0,2.0,27.0,4.0,4.0,43.7,168.2,130.0,2.0,4.9,NaN
11,130389.0,1.0,59.0,3.0,5.0,28.0,168.9,145.0,2.0,5.5,NaN
12,130390.0,2.0,31.0,3.0,3.0,46.0,163.3,113.0,2.0,5.9,NaN
13,130391.0,2.0,33.0,3.0,3.0,38.9,172.8,105.0,2.0,5.4,NaN
14,130392.0,2.0,74.0,3.0,5.0,43.0,151.5,154.0,2.0,5.6,NaN
15,130393.0,1.0,39.0,3.0,5.0,46.1,175.6,139.0,2.0,5.3,NaN
16,130394.0,1.0,51.0,3.0,5.0,24.4,177.3,99.0,2.0,4.8,88.0
17,130395.0,2.0,33.0,7.0,3.0,54.6,159.2,112.0,2.0,5.0,100.0
18,130396.0,2.0,56.0,3.0,4.0,27.3,154.9,122.0,2.0,5.0,104.0
19,130397.0,2.0,67.0,3.0,3.0,49.7,161.8,157.0,2.0,6.2,138.0

In [6]:
df.tail(10)

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
11923,142301.0,2.0,80.0,3.0,5.0,30.5,164.3,NaN,2.0,5.6,110.0
11924,142302.0,1.0,70.0,3.0,4.0,21.4,161.5,126.0,2.0,5.2,NaN
11925,142303.0,2.0,69.0,7.0,3.0,27.9,159.2,129.0,1.0,8.1,160.0
11926,142304.0,1.0,14.0,2.0,NaN,18.5,162.4,116.0,2.0,NaN,NaN
11927,142305.0,2.0,76.0,1.0,1.0,26.4,151.4,139.0,3.0,6.0,132.0
11928,142306.0,1.0,9.0,2.0,NaN,15.4,128.0,NaN,2.0,NaN,NaN
11929,142307.0,2.0,49.0,4.0,5.0,NaN,143.8,127.0,1.0,6.2,NaN
11930,142308.0,1.0,50.0,2.0,4.0,26.4,173.3,106.0,2.0,NaN,NaN
11931,142309.0,1.0,40.0,2.0,4.0,25.5,179.1,127.0,2.0,5.2,96.0
11932,142310.0,2.0,80.0,3.0,3.0,27.6,161.7,128.0,2.0,5.3,NaN

In [7]:
df.shape

(11933, 11)

In [8]:
df.shape[0]

11933

In [9]:
df.shape[1]

11

In [10]:
n_rows = df.shape[0]
n_cols = df.shape[1]
print(f"My dataset contains {n_rows} rows and {n_cols} columns")

My dataset contains 11933 rows and 11 columns

Boolean

In [11]:
1 + 1 == 3

False

In [12]:
1 + 1 == 2

True

In [13]:
True + True

2

In [14]:
True + False

1

Data Cleaning

In [15]:
#Missing values
#How big of a problem?
df['bmi'].head()
#NaN = Not a Number

0    27.0
1    33.5
2    29.7
3    23.8
4     NaN
Name: bmi, dtype: float64

In [16]:
#isna
#This function checks whether each row is na or not

df['bmi'].isna().head()

0    False
1    False
2    False
3    False
4     True
Name: bmi, dtype: bool

In [17]:
df['bmi'].isna().sum()

np.int64(3462)

We'll create a new dataset for people over 18 year only and see how many BMI values are missing.

In [18]:
df_adults = df[df['age'] > 18]

In [19]:
df_adults.shape[0]

7969

In [20]:
df_adults['age'].min()

19.0

In [21]:
df_adults['bmi'].isna().sum()

np.int64(1878)

Now it's your turn to do the same for education and have the output in f string

In [23]:
missing_ed_adults = df_adults['education'].isna().sum()

In [24]:
missing_ed_all = df['education'].isna().sum()

In [27]:
print(f"The number of rows with missing education in the entire dataset is {missing_ed_all},\n while it's only {missing_ed_adults} in the Adults dataset ")

The number of rows with missing education in the entire dataset is 4139,
 while it's only 175 in the Adults dataset

In [28]:
#Check missigness in the entire dataframe
df.isna().sum()

id                    0
gender                0
age                   0
race_ethnicity        0
education          4139
bmi                3462
height_cm          3434
systolic_bp        4416
has_diabetes        193
hba1c              5218
fasting_glucose    8261
dtype: int64

In [29]:
#Getting missigness as percentage
df.isna().mean()*100

id                  0.000000
gender              0.000000
age                 0.000000
race_ethnicity      0.000000
education          34.685326
bmi                29.011984
height_cm          28.777340
systolic_bp        37.006620
has_diabetes        1.617364
hba1c              43.727478
fasting_glucose    69.228191
dtype: float64

In [30]:
round(df.isna().mean()*100,1)

id                  0.0
gender              0.0
age                 0.0
race_ethnicity      0.0
education          34.7
bmi                29.0
height_cm          28.8
systolic_bp        37.0
has_diabetes        1.6
hba1c              43.7
fasting_glucose    69.2
dtype: float64

Treating missinginess

1- Dropping the rows with missing values

2- Fill in with the mean

In [31]:
#drop all rows that have any missing value
df_complete = df.dropna()

In [32]:
df_complete.shape[0]

3075

In [33]:
df_complete.isna().mean()*100

id                 0.0
gender             0.0
age                0.0
race_ethnicity     0.0
education          0.0
bmi                0.0
height_cm          0.0
systolic_bp        0.0
has_diabetes       0.0
hba1c              0.0
fasting_glucose    0.0
dtype: float64

In [34]:
#dropping only rows where select fields have missing values
df_complete_bmi = df.dropna(subset = ['bmi'])

In [35]:
#Verify it
df_complete_bmi['bmi'].isna().sum()

np.int64(0)

In [36]:
#Filling na with mean, zero, or with any other value
#Get the mean and assign it to a variable
mean_bp = df['systolic_bp'].mean()

In [39]:
print(round(mean_bp,2))

119.29

In [40]:
df['systolic_bp'] = df['systolic_bp'].fillna(mean_bp)

In [41]:
#Verify that the imputation/fillna worked
df['systolic_bp'].isna().sum()

np.int64(0)

Transform variables

In [42]:
def bmi_check(bmi):
  if bmi < 18.5:
    bmi_result = "Underweight"
  elif bmi < 25:
    bmi_result = "Normal"
  elif bmi < 30:
    bmi_result = "Overweight"
  else:
    bmi_result = "Obese"
  return bmi_result

In [43]:
df['bmi_category'] = df['bmi'].apply(bmi_check)

In [44]:
#Verify it
#value_counts()
df['bmi_category'].value_counts()

bmi_category
Obese          6161
Normal         2372
Overweight     2205
Underweight    1195
Name: count, dtype: int64

In [45]:
#New function called "cut"
df['bmi_category2'] = pd.cut(df['bmi'],
                             bins = [0, 18.5, 25, 30, 100],
                             labels = ["Underweight", "Normal", "Overweight", "Obese"])

In [46]:
#Verify it
df['bmi_category2'].value_counts()

bmi_category2
Obese          2666
Normal         2400
Overweight     2189
Underweight    1216
Name: count, dtype: int64

In [47]:
df['bmi_category2'].value_counts(dropna = False)

bmi_category2
NaN            3462
Obese          2666
Normal         2400
Overweight     2189
Underweight    1216
Name: count, dtype: int64

Next time, we'll start from transforming/decoding categorical data